server:
  port: 8088

eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: booking-server
          uri: lb://booking-server
          predicates:
            - Path=/api/v1/room/**
        - id: order-server
          uri: lb://order-server
          predicates:
            - Path=/api/v1/order/**, /api/gg/**
